name: Extension CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/fedora:32

    steps:
      - uses: actions/checkout@v2

      - name: Install host dependencies
        run: |
          dnf install -y nodejs dnf-plugins-core
          dnf copr enable -y fmuellner/gnome-tools
          dnf install -y gnome-extensions-tool

      - name: Install npm dependencies
        run: |
          npm install

      - name: Lint Source
        run: |
          npm run clean
          npm run lint:extension

      - name: Build
        run: |
          tsc
          node build/scripts/transpile.js

      - name: Lint package
        run: |
          npm run lint:package

      - name: Create archive artifact
        run: |
          cp metadata.json build/extension
          cp -r extension/ui extension/schemas build/extension
          gnome-extensions pack --force \
            --out-dir build/ build/extension \
            --extra-source=constants.js \
            --extra-source=src --extra-source=ui --extra-source=schemas

      - name: Upload archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: gestureImprovements@gestures.shell-extension.zip
          path: /pwd/build/gestureImprovements@gestures.shell-extension.zip
