name: Extension CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/fedora
      env:
        PWD: /pwd
      volumes:
        - ${{ github.workspace }}:/pwd

    steps:
      - uses: actions/checkout@v2

      - name: Install host dependencies
        run: |
          dnf install nodejs

      - name: Install npm dependencies
        run: |
          npm install

      - name: Lint Source
        run: |
          npm run clean
          npm run lint:extension

      - name: Build
        run: |
          tsc
          node build/scripts/transpile.js

      - name: Lint package
        run: |
          npm run lint:package

      - name: Create archive artifact
        run: |
          make pack

      - name: Upload archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: gestureImprovements@gestures.shell-extension.zip
          path: /pwd/build/gestureImprovements@gestures.shell-extension.zip
